name: Rust macOS

on: [push, pull_request]

jobs:
  test:
    name: Test Suite
    runs-on: macOS-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          brew install capnp
          python -m pip install --upgrade pip
      - name: Cargo Test
        run: cargo test --all
      - name: Install pycapnp dependencies and run test
        working-directory: ./python
        run: |
          python -m pip install cython
          CXXFLAGS=-fPIC CFLAGS=-fPIC python -m pip install -r requirements.txt
          python -m pytest -vvv

  build:
    name: Build
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - name: Install dependencies
        run: |
          brew install capnp
      - name: Cargo Install
        run: cargo install --path . --bins --examples --root dist
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: macos_release_binaries
          path: dist/bin
